name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: sudo apt-get install -y cmake lcov
      
    - name: Configure
      run: cmake -B build -DBUILD_TESTS=ON
      
    - name: Build
      run: cmake --build build
      
    - name: Run tests
      run: cd build && ctest --output-on-failure
      
    - name: Generate coverage
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/third-party/*' '*/tests/*' --output-file coverage.filtered.info
        genhtml coverage.filtered.info --output-directory coverage
        
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.filtered.info
