name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake lcov python3-pip
        pip install cpp-coveralls
        
    - name: Configure
      run: cmake -B build -DBUILD_TESTS=ON
      
    - name: Build
      run: cmake --build build
      
    - name: Run tests and generate coverage
      run: |
        cd build
        ./tests
        lcov --capture \
            --directory CMakeFiles/banking.dir/src \
            --directory CMakeFiles/tests.dir/tests \
            --output-file coverage.info
        lcov --remove coverage.info \
            '/usr/*' \
            '*/third-party/*' \
            '*/tests/*' \
            --output-file coverage.filtered.info
        genhtml coverage.filtered.info --output-directory coverage
        
    - name: Upload to Coveralls
      run: |
        coveralls \
          --root .. \
          --build-root build \
          --exclude tests \
          --exclude third-party \
          -i "src/" \
          --gcov-options '\-lp'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        COVERALLS_SERVICE_NAME: github
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage
